//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFDesign.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFDesign.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain.
        /// </summary>
        public static string captainString {
            get {
                return ResourceManager.GetString("captainString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of connection:.
        /// </summary>
        public static string connectionTypeString {
            get {
                return ResourceManager.GetString("connectionTypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draws.
        /// </summary>
        public static string drawsString {
            get {
                return ResourceManager.GetString("drawsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem with fetching data. Try again..
        /// </summary>
        public static string errorMsg {
            get {
                return ResourceManager.GetString("errorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem ocurred.
        /// </summary>
        public static string errorTitle {
            get {
                return ResourceManager.GetString("errorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit?.
        /// </summary>
        public static string exitMsg {
            get {
                return ResourceManager.GetString("exitMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit confirmation.
        /// </summary>
        public static string exitTitle {
            get {
                return ResourceManager.GetString("exitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifa code.
        /// </summary>
        public static string fifaCodeString {
            get {
                return ResourceManager.GetString("fifaCodeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Football results.
        /// </summary>
        public static string footballResultsTitle {
            get {
                return ResourceManager.GetString("footballResultsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal differential.
        /// </summary>
        public static string goalDiffString {
            get {
                return ResourceManager.GetString("goalDiffString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals against.
        /// </summary>
        public static string goalsAgainstString {
            get {
                return ResourceManager.GetString("goalsAgainstString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals.
        /// </summary>
        public static string goalsString {
            get {
                return ResourceManager.GetString("goalsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string languageString {
            get {
                return ResourceManager.GetString("languageString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Losses.
        /// </summary>
        public static string lossesString {
            get {
                return ResourceManager.GetString("lossesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches played.
        /// </summary>
        public static string matchesPlayedString {
            get {
                return ResourceManager.GetString("matchesPlayedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player info.
        /// </summary>
        public static string playerInfoTitle {
            get {
                return ResourceManager.GetString("playerInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string positionString {
            get {
                return ResourceManager.GetString("positionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to save current settings?.
        /// </summary>
        public static string saveMsg {
            get {
                return ResourceManager.GetString("saveMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string saveString {
            get {
                return ResourceManager.GetString("saveString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save confirmation.
        /// </summary>
        public static string saveTitle {
            get {
                return ResourceManager.GetString("saveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scored goals.
        /// </summary>
        public static string scoredGoalsString {
            get {
                return ResourceManager.GetString("scoredGoalsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen size:.
        /// </summary>
        public static string screenSizeString {
            get {
                return ResourceManager.GetString("screenSizeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settingsTitle {
            get {
                return ResourceManager.GetString("settingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shirt number.
        /// </summary>
        public static string shirtNumberString {
            get {
                return ResourceManager.GetString("shirtNumberString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team info.
        /// </summary>
        public static string teamInfoTitle {
            get {
                return ResourceManager.GetString("teamInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of championship:.
        /// </summary>
        public static string typeOfChampString {
            get {
                return ResourceManager.GetString("typeOfChampString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wins.
        /// </summary>
        public static string winsString {
            get {
                return ResourceManager.GetString("winsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow cards.
        /// </summary>
        public static string yellowCardsString {
            get {
                return ResourceManager.GetString("yellowCardsString", resourceCulture);
            }
        }
    }
}
