//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormsDesign {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinFormsDesign.MessageRes", typeof(MessageRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain.
        /// </summary>
        public static string captainString {
            get {
                return ResourceManager.GetString("captainString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players ranked by cards.
        /// </summary>
        public static string cardsTitle {
            get {
                return ResourceManager.GetString("cardsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For additional questions, contact me at: asim.ribo21@gmail.com.
        /// </summary>
        public static string contactMsg {
            get {
                return ResourceManager.GetString("contactMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string contactTitle {
            get {
                return ResourceManager.GetString("contactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem with fetching data. Please try again..
        /// </summary>
        public static string errorMsg {
            get {
                return ResourceManager.GetString("errorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem occured.
        /// </summary>
        public static string errorTitle {
            get {
                return ResourceManager.GetString("errorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit?.
        /// </summary>
        public static string exitMsg {
            get {
                return ResourceManager.GetString("exitMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit confirmation.
        /// </summary>
        public static string exitTitle {
            get {
                return ResourceManager.GetString("exitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of fans.
        /// </summary>
        public static string fansNumberString {
            get {
                return ResourceManager.GetString("fansNumberString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may choose only 3 favorite players..
        /// </summary>
        public static string favoritePlayersFull {
            get {
                return ResourceManager.GetString("favoritePlayersFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games ranked by fans.
        /// </summary>
        public static string gamesTitle {
            get {
                return ResourceManager.GetString("gamesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to goals.
        /// </summary>
        public static string goalsString {
            get {
                return ResourceManager.GetString("goalsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players ranked by goals.
        /// </summary>
        public static string goalsTitle {
            get {
                return ResourceManager.GetString("goalsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string locationString {
            get {
                return ResourceManager.GetString("locationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load pictures.
        /// </summary>
        public static string ofdTitle {
            get {
                return ResourceManager.GetString("ofdTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string playerString {
            get {
                return ResourceManager.GetString("playerString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This saves current application settings. Are you sure?.
        /// </summary>
        public static string settingsMsg {
            get {
                return ResourceManager.GetString("settingsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settingsTitle {
            get {
                return ResourceManager.GetString("settingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow cards.
        /// </summary>
        public static string yellowCardsString {
            get {
                return ResourceManager.GetString("yellowCardsString", resourceCulture);
            }
        }
    }
}
